-- CreateTable
CREATE TABLE `Elements` (
    `number` INTEGER NOT NULL,
    `name_tr` TEXT NULL,
    `name_en` TEXT NULL,
    `alternate_name` TEXT NULL,
    `symbol` TEXT NULL,
    `cas_number` TEXT NULL,
    `cid_number` TEXT NULL,
    `dot_number` TEXT NULL,
    `rtecs_number` TEXT NULL,
    `mendeleev_number` INTEGER NULL,
    `pettifor_number` INTEGER NULL,
    `eu_number` TEXT NULL,
    `space_group_number` TEXT NULL,
    `glawe_number` INTEGER NULL,
    `atomic_mass` TEXT NULL,
    `atomic_mass_uncertainty` TEXT NULL,
    `xpos` INTEGER NULL,
    `ypos` INTEGER NULL,
    `period` INTEGER NULL,
    `group` TEXT NULL,
    `block` TEXT NULL,
    `category` TEXT NULL,
    `electrical_type` TEXT NULL,
    `geochemical_class` TEXT NULL,
    `goldschmidt_class` TEXT NULL,
    `gas_phase` TEXT NULL,
    `allotrope_names` TEXT NULL,
    `appearance` TEXT NULL,
    `abundance_in_earth_crust_c1` TEXT NULL,
    `abundance_in_earth_crust_c2` TEXT NULL,
    `abundance_in_earth_crust_c3` TEXT NULL,
    `abundance_in_earth_crust_c4` TEXT NULL,
    `abundance_in_earth_crust_c5` TEXT NULL,
    `abundance_in_earth_crust_c6` TEXT NULL,
    `abundance_in_earth_crust_u1` TEXT NULL,
    `abundance_in_earth_crust_u2` TEXT NULL,
    `abundance_urban_soil` TEXT NULL,
    `abundance_meteorite` TEXT NULL,
    `abundance_seawater_w1` TEXT NULL,
    `abundance_seawater_w2` TEXT NULL,
    `abundance_humans` TEXT NULL,
    `abundance_in_humans_2` TEXT NULL,
    `abundance_sun_s1` TEXT NULL,
    `abundance_solar_system_y1` TEXT NULL,
    `abundance_solar_system_y2` TEXT NULL,
    `atomic_radius_empirical` TEXT NULL,
    `atomic_radius_calculated` TEXT NULL,
    `atomic_radius_vanderwaals` TEXT NULL,
    `vdw_radius_bondi` TEXT NULL,
    `vdw_radius_truhlar` TEXT NULL,
    `vdw_radius_rt` TEXT NULL,
    `atomic_radius_rahm` TEXT NULL,
    `vdw_radius_batsanov` TEXT NULL,
    `vdw_radius_dreiding` TEXT NULL,
    `vdw_radius_uff` TEXT NULL,
    `vdw_radius_mm3` TEXT NULL,
    `vdw_radius_alvarez` TEXT NULL,
    `covalent_radius_bragg` TEXT NULL,
    `atomic_radius_covalent_single_bond` TEXT NULL,
    `atomic_radius_covalent_triple_bond` TEXT NULL,
    `covalent_radius_cordero` TEXT NULL,
    `covalent_radius_pyykko` INTEGER NULL,
    `covalent_radius_pyykko_double` TEXT NULL,
    `covalent_radius_pyykko_triple` TEXT NULL,
    `metallic_radius_mendeleev` TEXT NULL,
    `metallic_radius_c12` TEXT NULL,
    `atomic_radius_metallic` TEXT NULL,
    `jmol_color` TEXT NULL,
    `molcas_gv_color` TEXT NULL,
    `cpk_color` TEXT NULL,
    `refractive_index` TEXT NULL,
    `phase_at_stp` TEXT NULL,
    `melt_use` TEXT NULL,
    `melt_WEL` TEXT NULL,
    `melt_CRC` TEXT NULL,
    `melt_LNG` TEXT NULL,
    `boil_use` TEXT NULL,
    `boil_WEL` TEXT NULL,
    `boil_CRC` TEXT NULL,
    `boil_LNG` TEXT NULL,
    `boil_Zhang` TEXT NULL,
    `curie_point` TEXT NULL,
    `critical_temperature` TEXT NULL,
    `flashpoint` TEXT NULL,
    `superconducting_point` TEXT NULL,
    `autoignition_point` TEXT NULL,
    `critical_pressure` TEXT NULL,
    `density_rt` TEXT NULL,
    `density_solid_WEL` TEXT NULL,
    `density_solid_LNG` TEXT NULL,
    `density_solid_CRC` TEXT NULL,
    `density_liquid_cr2` TEXT NULL,
    `density_gas` TEXT NULL,
    `molar_volume` TEXT NULL,
    `atomic_volume` TEXT NULL,
    `enthalpy_of_fusion` TEXT NULL,
    `heat_of_fusion_crc` TEXT NULL,
    `heat_of_fusion_lng` TEXT NULL,
    `heat_of_fusion_wel` TEXT NULL,
    `evaporation_heat` TEXT NULL,
    `heat_of_vaporization_crc` TEXT NULL,
    `heat_of_vaporization_lng` TEXT NULL,
    `heat_of_vaporization_wel` TEXT NULL,
    `heat_of_vaporization_zhang` TEXT NULL,
    `heat_of_combustion` TEXT NULL,
    `molar_heat` TEXT NULL,
    `specific_heat_capacity` TEXT NULL,
    `specific_heat_crc` TEXT NULL,
    `specific_heat_wel` TEXT NULL,
    `specific_heat_lng` TEXT NULL,
    `thermal_conductivity` TEXT NULL,
    `thermal_expansion` TEXT NULL,
    `adiabatic_index` TEXT NULL,
    `speed_of_sound_longitudinal` TEXT NULL,
    `speed_of_sound_transversal` TEXT NULL,
    `speed_of_sound_extensional` TEXT NULL,
    `speed_of_sound_fluid` TEXT NULL,
    `electrical_resistivity_80K` TEXT NULL,
    `electrical_resistivity_273K` TEXT NULL,
    `electrical_resistivity_293K` TEXT NULL,
    `electrical_resistivity_298K` TEXT NULL,
    `electrical_resistivity_300K` TEXT NULL,
    `electrical_resistivity_500K` TEXT NULL,
    `magnetic_ordering` TEXT NULL,
    `neel_point` TEXT NULL,
    `magnetic_susceptibility` TEXT NULL,
    `shear_modulus` TEXT NULL,
    `bulk_modulus` TEXT NULL,
    `poisson_ratio` TEXT NULL,
    `youngs_modulus` TEXT NULL,
    `mohs_hardness` TEXT NULL,
    `brinell_hardness` TEXT NULL,
    `vickers_hardness` TEXT NULL,
    `description` TEXT NULL,
    `language_of_origin` TEXT NULL,
    `origin_of_word` TEXT NULL,
    `original_word` TEXT NULL,
    `meaning` TEXT NULL,
    `symbol_origin` TEXT NULL,
    `etymological_description` TEXT NULL,
    `observed_predicted_by` TEXT NULL,
    `observation_or_discovery_year` TEXT NULL,
    `discovery_location` TEXT NULL,
    `isolated_sampled_by` TEXT NULL,
    `isolation_sample_year` TEXT NULL,
    `named_by` TEXT NULL,
    `sources` TEXT NULL,
    `uses` TEXT NULL,
    `spectral_img` TEXT NULL,
    `is_radioactive` INTEGER NULL,
    `decay_mode` TEXT NULL,
    `half_life` TEXT NULL,
    `lifetime` TEXT NULL,
    `neutron_mass_absorption` TEXT NULL,
    `neutron_cross_section` TEXT NULL,
    `proton_affinity` TEXT NULL,
    `electron_affinity_eV` TEXT NULL,
    `electron_affinity_kJmol` TEXT NULL,
    `electronegativity_pauling` TEXT NULL,
    `electronegativity_allen` TEXT NULL,
    `electronegativity_ghosh` TEXT NULL,
    `dipole_polarizability` TEXT NULL,
    `dipole_polarizability_unc` TEXT NULL,
    `c6_gb` TEXT NULL,
    `c6_coeff` TEXT NULL,
    `lattice_constant_internal_default_radii` TEXT NULL,
    `lattice_constant` TEXT NULL,
    `lattice_structure` TEXT NULL,
    `lattice_angles` TEXT NULL,
    `oxidation_states` TEXT NULL,
    `electron_configuration` TEXT NULL,
    `quantum_number` TEXT NULL,
    `electron_configuration_semantic` TEXT NULL,
    `shells-0` INTEGER NULL,
    `shells-1` INTEGER NULL,
    `shells-2` INTEGER NULL,
    `shells-3` INTEGER NULL,
    `shells-4` INTEGER NULL,
    `shells-5` INTEGER NULL,
    `shells-6` INTEGER NULL,
    `shells-7` INTEGER NULL,
    `ionization_energies-0` TEXT NULL,
    `ionization_energies-1` TEXT NULL,
    `ionization_energies-2` TEXT NULL,
    `ionization_energies-3` TEXT NULL,
    `ionization_energies-4` TEXT NULL,
    `ionization_energies-5` TEXT NULL,
    `ionization_energies-6` TEXT NULL,
    `ionization_energies-7` TEXT NULL,
    `ionization_energies-8` TEXT NULL,
    `ionization_energies-9` TEXT NULL,
    `ionization_energies-10` TEXT NULL,
    `ionization_energies-11` TEXT NULL,
    `ionization_energies-12` TEXT NULL,
    `ionization_energies-13` TEXT NULL,
    `ionization_energies-14` TEXT NULL,
    `ionization_energies-15` TEXT NULL,
    `ionization_energies-16` TEXT NULL,
    `ionization_energies-17` TEXT NULL,
    `ionization_energies-18` TEXT NULL,
    `ionization_energies-19` TEXT NULL,
    `ionization_energies-20` TEXT NULL,
    `ionization_energies-21` TEXT NULL,
    `ionization_energies-22` TEXT NULL,
    `ionization_energies-23` TEXT NULL,
    `ionization_energies-24` TEXT NULL,
    `ionization_energies-25` TEXT NULL,
    `ionization_energies-26` TEXT NULL,
    `ionization_energies-27` TEXT NULL,
    `ionization_energies-28` TEXT NULL,
    `ionization_energies-29` TEXT NULL,
    `wikipedia` TEXT NULL,
    `ea_content_id` INTEGER NULL,

    PRIMARY KEY (`number`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Isotopes` (
    `id` INTEGER NOT NULL DEFAULT 0,
    `atomic_number_unique` INTEGER NULL,
    `known_isotopes` TEXT NULL,
    `stable_isotopes` TEXT NULL,
    `is_monoisotopic` BOOLEAN NULL,
    `atomic_number_notunique` INTEGER NULL,
    `mass` DOUBLE NULL,
    `abundance` DOUBLE NULL,
    `mass_number` INTEGER NULL,
    `mass_uncertainty` VARCHAR(30) NULL,
    `is_radioactive` BOOLEAN NULL,
    `half_life` VARCHAR(30) NULL,
    `half_life_unit` VARCHAR(30) NULL,
    `spin` DOUBLE NULL,
    `g_factor` DOUBLE NULL,
    `quadrupole_moment` DOUBLE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Compounds` (
    `id` INTEGER NOT NULL DEFAULT 0,
    `record_number` INTEGER NOT NULL,
    `record_title` TEXT NOT NULL,
    `iupac_name` TEXT NOT NULL,
    `inchi` TEXT NOT NULL,
    `inchi_key` TEXT NOT NULL,
    `canonical_smiles` TEXT NOT NULL,
    `icsc_number` INTEGER NOT NULL,
    `rtecs_number` TEXT NOT NULL,
    `unii` TEXT NOT NULL,
    `fema_number` INTEGER NOT NULL,
    `dss_tox_substance_id` TEXT NOT NULL,
    `nci_thesaurus_code` TEXT NOT NULL,
    `molecular_weight` DOUBLE NOT NULL,
    `compound_is_canonicalized` TEXT NOT NULL,
    `xlogp3` DOUBLE NOT NULL,
    `hydrogen_bond_donor_count` INTEGER NOT NULL,
    `hydrogen_bond_acceptor_count` INTEGER NOT NULL,
    `rotatable_bond_count` INTEGER NOT NULL,
    `exact_mass` JSON NOT NULL,
    `monoisotopic_mass` JSON NOT NULL,
    `topological_polar_surface_area` JSON NOT NULL,
    `heavy_atom_count` INTEGER NOT NULL,
    `formal_charge` INTEGER NOT NULL,
    `complexity` INTEGER NOT NULL,
    `isotope_atom_count` INTEGER NOT NULL,
    `defined_atom_stereocenter_count` INTEGER NOT NULL,
    `undefined_atom_stereocenter_count` INTEGER NOT NULL,
    `defined_bond_stereocenter_count` INTEGER NOT NULL,
    `undefined_bond_stereocenter_count` INTEGER NOT NULL,
    `covalently-bonded_unit_count` INTEGER NOT NULL,
    `taste` TEXT NOT NULL,
    `logp` TEXT NOT NULL,
    `henrys_law_constant` TEXT NOT NULL,
    `atmospheric_oh_rate_constant` TEXT NOT NULL,
    `stability_shelf_life` TEXT NOT NULL,
    `viscosity` TEXT NOT NULL,
    `heat_of_combustion` TEXT NOT NULL,
    `heat_of_vaporization` TEXT NOT NULL,
    `ph` TEXT NOT NULL,
    `surface_tension` TEXT NOT NULL,
    `ionization_potential` TEXT NOT NULL,
    `polymerization` TEXT NOT NULL,
    `refractive_index` TEXT NOT NULL,
    `food_additive_classes` TEXT NOT NULL,
    `agrochemical_category` TEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
